; ------------------------------------------------------------
; @i ...: Includes - Runner
; ------------------------------------------------------------
#Include <Tools\CleanInputBox>
#Include <Tools\CoordInfo>
#Include <Tools\Counter>
#Include <Tools\FileSystemSearch>
#Include <Tools\Hider>
#Include <Tools\HoverScreenshot>
#Include <Tools\Info>
#Include <Tools\InternetSearch>
#Include <Tools\KeycodeGetter>
#Include <Tools\Message_Post_Send.c2v2>
#Include <Tools\Point>
#Include <Tools\RelativeCoordInfo>
#Include <Tools\Snake>
#Include <Tools\StateBulb>
#Include <Tools\ToggleInfo>
#Include <Tools\WindowGetter>
#Include <Tools\WindowInfo>
; ------------------------------------------------------------